config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }


  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'ruby-on-rails-portfolio', to: 'portfolios#ruby_on_rails'
  get 'vue-portfolio', to: 'portfolios#vue'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'messages#new', as: 'new_message'
  post 'contact', to: 'messages#create', as: 'create_message'

  resources :topics, only: [:index, :show]
  resources :resources, only: [:index, :show]
  resources :resource_categories, only: [:index, :show]
  resources :resource_topics, only: [:index, :show]


  resources :blogs do
    member do
      get :toggle_status
    end
  end

  resources :resource_items, except: [:index] do
    resources :resource_comments
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1 }


  validates_presence_of :title, :body, :topic_id, :status

  belongs_to :topic

  has_many :comments, dependent: :destroy


  scope :hide_drafts, -> { where(status: 'published') }

  def self.protect_drafts user
    if user.has_role?(:site_admin)
      all
    else
      hide_drafts
    end
  end

  def self.by_recent
    order("created_at DESC")
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  skip_before_action :authenticate_user!

  before_action :set_blog, only: [:edit, :update, :destroy, :toggle_status]
  layout "blog"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, site_admin: :all

  def index
    @blogs = Blog.protect_drafts(current_user).by_recent.page(params[:page]).per(5)
    @page_title = "Blog"
  end

  def show
    @blog = Blog.includes(:comments).friendly.find(params[:id])
    if logged_in?(:site_admin) || @blog.published?
      @comment = Comment.new
      @page_title = @blog.title
      @seo_keywords = @blog.body
    else
      redirect_to blogs_path, notice: "You are not authorized to access this page"
    end
  end

  def new
    @blog = Blog.new
    @page_title = "Create a New Post"
  end

  def edit
    @page_title = "Editing \"" + @blog.title + "\""
  end

  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Your post has been created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'The post has been updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'The post has been deleted.' }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Post status has been updated.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body, :topic_id, :status, :created_at)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def gravatar_helper user
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", class: 'img-fluid'
  end

  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      if code and language
        CodeRay.scan(code, language).div
      end
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(escape_html: true, hard_wrap: true, with_toc_data: true)

    options = {
      no_intra_emphasis: true,
      tables: true,
      fenced_code_blocks: true,
      autolink: true,
      disable_indented_code_blocks: true,
      strikethrough: true,
      lax_spacing: true,
      space_after_headers: true,
      superscript: true,
      underline: true,
      highlight: true,
      quote: true,
      footnotes: true,
      lax_html_blocks: true,
      with_toc_data: true

    }

    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)

    markdown_to_html.render(text).html_safe
  end

  def blog_status_color blog
    'color: #d9534f;' if blog.draft?
  end
end

app/views/blogs/_admin_actions.html.haml
- if logged_in?(:site_admin)
  %nav.breadcrumb.blogcrumb
    = link_to toggle_status_blog_path(blog) do
      %i{'class' => 'fa fa-file-text breadcrumb-item', 'style' => blog_status_color(blog)}
    = link_to edit_blog_path(blog) do
      %i.fa.fa-pencil-square-o.breadcrumb-item
    = button_to @blog, :method => :delete, :data => { :confirm => "Are you sure you want to delete that post?" }, :class => 'button button--to-delete' do
      %i.fa.fa-trash.breadcrumb-item

app/views/blogs/_blog.html.haml
.page-section
  %h2.section-title= link_to blog.title, blog
  %p= "Published #{distance_of_time_in_words blog.created_at, Time.now} ago"
  %p= pluralize blog.comments.count, "comment"

  = render partial: 'blogs/admin_actions', locals: {:blog => blog}

  %div
    = markdown blog.body

app/views/blogs/_form.html.haml
= simple_form_for blog do |f|
  - if blog.errors.any?
    - blog.errors.full_messages.each do |error|
      = alert_generator(error, :error, "Error")
  %div
    = f.label :title
    = f.text_field :title
  %div
    = f.label :created_at, "Publish Date"
    = f.date_field :created_at, value: (blog.created_at || Time.now)
  %div
    = f.input :topic_id, collection: Topic.all.map{|topic| [topic.title, topic.id]}, selected: 1, "aria-label" => "Topic"
    / = f.collection_select :topic_id, Topic.all, :id, :title, {:prompt => "Please select a topic"}, "aria-label" => "Topic"
  %div
    = f.label :body
    = f.text_area :body, rows: 15
  %div
    = f.input :photos, as: :file, input_html: { multiple: true }
  %div
    = f.submit

app/views/blogs/edit.html.haml
%div
  %h1= "Editing #{@blog.title}"
  = render 'form', blog: @blog

  = link_to 'View Post', @blog
  = link_to 'Back to Blog', blogs_path

app/views/blogs/index.html.haml
%div
  .row.row--full-height.relative
    .row__medium-1-2
      = image_tag 'https://res.cloudinary.com/adelcloud/image/upload/v1583819796/christian-fregnan-pvyWk-nXDNs-unsplash_drhzer.jpg', :alt => 'Blog', :class => 'img--full-height img--background img--grayscaled'
      .overlay.overlay--dark-color
      .container.container--full-height.container--centered-vh
        %h1.section-title= "Blog Posts"
.page-section
  .container
    = paginate @blogs
    = render partial: 'blog', collection: @blogs
    = paginate @blogs

app/views/blogs/new.html.haml
%div
  %h1= @page_title
  = render 'form', blog: @blog
  = link_to 'Back to Blog', blogs_path
  

app/views/blogs/show.html.haml
.row.row--short.relative
  .row__medium-1-2
    = image_tag 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80', :alt => 'Computer', :class => 'img--full-height img--background img--grayscaled'
    .overlay.overlay--dark-color
.page-section
  .container
    %h2.section-title= @blog.title
    %p= "Published #{distance_of_time_in_words(@blog.created_at, Time.now)} ago"
    %p= pluralize @blog.comments.count, "comment"
    %nav.breadcrumb
      = link_to 'Home', root_url, class: "breadcrumb-item"
      %span.breadcrumb-item.active= @blog.title
      - if logged_in?(:site_admin)
        %div
          = link_to edit_blog_path(@blog) do
            %i.fa.fa-pencil-square-o
          = button_to @blog, :method => :delete, :data => { :confirm => "Are you sure you want to delete that post?" }, :class => 'button button--to-delete' do
            %i.fa.fa-trash

    .generic-content-container
      - @blog.photos.each do |photo|
        %li= cl_image_tag photo.key, height: 300, width: 400
      = markdown @blog.body
    %h3.section-title= "Comments"
    = render "comments/comment_form"
    #comments{"data-blog-id" => @blog.id}
      = render partial: 'comments/comment', collection: @blog.comments.by_recent