config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }


  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'ruby-on-rails-portfolio', to: 'portfolios#ruby_on_rails'
  get 'vue-portfolio', to: 'portfolios#vue'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'messages#new', as: 'new_message'
  post 'contact', to: 'messages#create', as: 'create_message'

  resources :topics, only: [:index, :show]
  resources :resources, only: [:index, :show]
  resources :resource_categories, only: [:index, :show]
  resources :resource_topics, only: [:index, :show]


  resources :blogs do
    member do
      get :toggle_status
    end
  end

  resources :resource_items, except: [:index] do
    resources :resource_comments
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  # has_many :technologies
  # accepts_nested_attributes_for :technologies, allow_destroy: true, reject_if: lambda { |attrs| attrs['name'].blank? }

  validates_presence_of :title, :body

  # has_one_attached :main_image
  # has_one_attached :thumb_image

  def self.by_position
    order("position ASC")
  end

  scope :ruby_on_rails, -> { where(subtitle: 'Ruby on Rails') }

  scope :vue, -> { where(subtitle: 'Vue') }
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  skip_before_action :authenticate_user!

  layout 'portfolio'
  access all: [:show, :index, :ruby_on_rails, :vue], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all

  def index
    # Pass Portfolios to the view
    @portfolio_items = Portfolio.by_position
    @page_title = "Portfolio"
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end
    render nothing: true
  end

  def ruby_on_rails
    @ruby_on_rails_portfolio_items = Portfolio.ruby_on_rails
  end

  def vue
    @vue_portfolio_items = Portfolio.vue
  end

  def show
    # Look up portfolio item
    @portfolio_item = Portfolio.find(params[:id])
    @page_title = @portfolio_item.title
  end

  def new
    # Create a new Portfolio instance
    @portfolio_item = Portfolio.new
    @page_title = "Create a New Portfolio Item"
  end

  def edit
    # Look up portfolio item
    @portfolio_item = Portfolio.find(params[:id])
    @page_title = "Editing \"" + @portfolio_item.title + "\""
  end

  def create
    # Validate new Portfolio
    @portfolio_item = Portfolio.new(portfolio_params)
    # What happens next
    respond_to do |format|
      # If successfully created
      if @portfolio_item.save
        # Redirect to portfolios index
        format.html { redirect_to portfolios_path, notice: 'Your portfolio item has been created.' }
      else
        # Stay on new page for correction
        format.html { render :new }
      end
    end
  end

  def update
    # Look up portfolio item
    @portfolio_item = Portfolio.find(params[:id])
    # What happens next
    respond_to do |format|
      # Validate changes
      if @portfolio_item.update(portfolio_params)
        # Redirect to portfolios index
        format.html { redirect_to portfolios_path, notice: 'The portfolio item has been updated.' }
      else
        # Stay on edit page for correction
        format.html { render :edit }
      end
    end
  end

  def destroy
    # Look up portfolio item
    @portfolio_item = Portfolio.find(params[:id])
    # Destroy/Delete it
    @portfolio_item.destroy
    # What happens next
    respond_to do |format|
      # Redirect to portfolios index
      format.html { redirect_to portfolios_url, notice: 'The portfolio item has been deleted.' }
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def portfolio_params
    params.require(:portfolio).permit(:title,
                                      :subtitle,
                                      :body,
                                      :main_image,
                                      :thumb_image,
                                      technologies_attributes: [:id, :name, :_destroy]
                                      )
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(width:, height:)
    "https://placehold.it/#{width}x#{height}"
  end

  def portfolio_img img, type
    if !img.nil?
      img
    elsif type == 'thumb'
      image_generator(width: '350', height: '200')
    elsif type == 'main'
      image_generator(width: '600', height: '400')
    end
  end
end

app/views/portfolios/_form.html.haml
= form_for @portfolio_item do |f|
  - if @portfolio_item.errors.any?
    - @portfolio_item.errors.full_messages.each do |error|
      = alert_generator error, :error, "Error"
  %br
  %br
  %br
  %br
  %br
  %br
  %div
    = f.label :title
    = f.text_field :title, rows: 4, cols: 80
  %div
    = f.label :subtitle
    = f.text_field :subtitle, rows: 4, cols: 80
  %div
    = f.label :main_image, "Main Image URL"
    = f.text_field :main_image
  %div
    = f.label :thumb_image, "Thumbnail Image URL"
    = f.text_field :thumb_image
  %div
    = f.label :body
    = f.text_area :body, :rows => 13
  %div
    = f.submit

app/views/portfolios/_portfolio_item.html.haml
.row__medium-1-3
  = cl_image_tag portfolio_item.thumb_image, :alt => "#{[portfolio_item.title]}", :style => 'object-fit: cover; width: 350px!important; height: 200px!important;'
  %h3
    = link_to portfolio_item.title, portfolio_show_path(portfolio_item)
    %small= portfolio_item.subtitle

app/views/portfolios/_technology_fields.html.haml
%div
  = f.text_field :name, "aria-label" => :name
  / = link_to_remove_association "Remove Technology", f

app/views/portfolios/edit.html.haml
%h1= @page_title
= render "form", :portfolio_item => @portfolio_item

app/views/portfolios/index.html.haml
.row.row--full-height.relative
  .row__medium-1-2
    = image_tag 'https://images.unsplash.com/photo-1524654458049-e36be0721fa2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=8', :alt => 'Computer', :class => 'img--full-height img--background img--grayscaled'
    .overlay.overlay--dark-color
.page-section
  .container
    %h1.section-title= "Portfolio"
    = source_helper "alert alert-info"
    .row.row--gutters
      = render :partial => "portfolio_item", :collection => @portfolio_items

app/views/portfolios/new.html.haml
%h1= @page_title
= render "form", :portfolio_item => @portfolio_item

app/views/portfolios/ruby_on_rails.html.haml
%h1= "Ruby on Rails Portfolio Items"
= link_to "Add a Portfolio Item", new_portfolio_path if logged_in?(:site_admin)
- @ruby_on_rails_portfolio_items.each do |portfolio_item|
  %div
    %h2= = link_to portfolio_item.title, portfolio_show_path(portfolio_item)
    %p= portfolio_item.subtitle
    = image_tag portfolio_item.thumb_image, :alt => portfolio_item.title
    %div= portfolio_item.body
    %p= link_to "Edit Item", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin)
    %p= link_to "Delete Item", portfolio_item, :method => :delete, :data => {:confirm => "Are you sure you want to delete that portfolio item?"} if logged_in?(:site_admin)
    

app/views/portfolios/show.html.haml
= cl_image_tag @portfolio_item.main_image, :width => "100%"
.page-section
  .container
    %h2.section-title= @portfolio_item.title
    %p= @portfolio_item.subtitle
    .generic-content-container
      %p= markdown @portfolio_item.body
- if logged_in?(:site_admin)
  .container
    = link_to "Edit Item", edit_portfolio_path(@portfolio_item)

app/views/portfolios/vue.html.haml
%h1= "Vue Portfolio Items"
= link_to "Add a Portfolio Item", new_portfolio_path if logged_in?(:site_admin)
- @vue_portfolio_items.each do |portfolio_item|
  %div
    %h2= = link_to portfolio_item.title, portfolio_show_path(portfolio_item)
    %p= portfolio_item.subtitle
    = image_tag portfolio_item.thumb_image, :alt => portfolio_item.title
    %div= portfolio_item.body
    %p= link_to "Edit Item", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin)
    %p= link_to "Delete Item", portfolio_item, :method => :delete, :data => {:confirm => "Are you sure you want to delete that portfolio item?"} if logged_in?(:site_admin)
    