config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }


  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'ruby-on-rails-portfolio', to: 'portfolios#ruby_on_rails'
  get 'vue-portfolio', to: 'portfolios#vue'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'messages#new', as: 'new_message'
  post 'contact', to: 'messages#create', as: 'create_message'

  resources :topics, only: [:index, :show]
  resources :resources, only: [:index, :show]
  resources :resource_categories, only: [:index, :show]
  resources :resource_topics, only: [:index, :show]


  resources :blogs do
    member do
      get :toggle_status
    end
  end

  resources :resource_items, except: [:index] do
    resources :resource_comments
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/models/resource_item.rb
class ResourceItem < ApplicationRecord
  belongs_to :resource_topic

  enum status: { draft: 0, published: 1 }


  validates_presence_of :title, :body, :resource_topic_id, :status


  has_many :resource_comments, dependent: :destroy
  has_many :checkboxes, dependent: :destroy
  has_many :questions, dependent: :destroy
  accepts_nested_attributes_for :questions, reject_if: lambda {|attributes| attributes['question_text'].blank?}


  scope :hide_drafts, -> { where(status: 'published') }

  def self.protect_drafts user
    if user.has_role?(:site_admin)
      all
    else
      hide_drafts
    end
  end

  def self.by_recent
    order("created_at ASC")
  end
end

app/controllers/resource_items_controller.rb
class ResourceItemsController < ApplicationController
  skip_before_action :authenticate_user!

  before_action :set_item, only: [:edit, :update, :destroy, :toggle_status]
  layout "resource_item"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, site_admin: :all

  def index
    @resource_items = ResourceItem.protect_drafts(current_user).by_recent.page(params[:page]).per(5)
    @page_title = "Class"
  end

  def show
    @resource_item = ResourceItem.includes(:resource_comments).find(params[:id])
    # if logged_in?(:site_admin) || @resource_item.published?
    if true
      @resource_comment = ResourceComment.new
      @resource_comment.resource_item_id = @resource_item.id
      @page_title = @resource_item.title
      # @seo_keywords = @resource_item.body
    else
      redirect_to resource_items_path, notice: "You are not authorized to access this page"
    end
  end

  def new
    @resource_item = ResourceItem.new
    10.times { @resource_item.questions.build }
    5.times { @resource_item.checkboxes.build }
    @page_title = "Create a New Post"
  end

  def edit
    @page_title = "Editing \"" + @resource_item.title + "\""
  end

  def create
    @resource_item = ResourceItem.new(item_params)

    respond_to do |format|
      if @resource_item.save
        format.html { redirect_to @resource_item, notice: 'Your post has been created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @resource_item.update(item_update_params)
        format.html { redirect_to @resource_item, notice: 'The post has been updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @resource_item.destroy
    respond_to do |format|
      format.html { redirect_to resource_items_url, notice: 'The post has been deleted.' }
    end
  end

  def toggle_status
    if @resource_item.draft?
      @resource_item.published!
    elsif @resource_item.published?
      @resource_item.draft!
    end
    respond_to do |format|
      format.html { redirect_to resource_items_url, notice: 'Post status has been updated.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @resource_item = ResourceItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:resource_item).permit(:title, :cdong_task, :body, :written_task, :resource_topic_id, :status, :checbox, :created_at, questions_attributes: [:question_text, :option1, :explanation1, :option2, :explanation2, :option3, :explanation3], checkboxes_attributes: [:label])
    end
    def item_update_params
      params.require(:resource_item).permit(:title, :cdong_task, :body, :written_task, :resource_topic_id, :status, :checbox, :created_at, checkboxes_attributes: [:label])
    end


end

app/helpers/resource_items_helper.rb
# create custom tags for redcarpet to insert youtube|vimeo iframes in
# your document.
# ::usage:: vid(youtube, 123456)

module ResourceItemsHelper
  def gravatar_helper user
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", class: 'img-fluid'
  end

  def resource_item_status_color resource_item
    'color: #d9534f;' if resource_item.draft?
  end

  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      if code and language
        CodeRay.scan(code, language).div
      end
    end
    def autolink(link, link_type)
      case link_type
        when :url then url_link(link)
        when :email then email_link(link)
      end
    end
    def url_link(link)
      case link
        when /^https:\/\/repl/ then repl_link(link)
        else normal_link(link)
      end
    end
    def repl_link(link)
      print('repl link here')
      parameters_start = link.index('?')
      video_id = link[16..(parameters_start ? parameters_start-1 : -1)]
      "<iframe width=\"560\" height=\"315\" src=\"//https://repl.it/repls/#{video_id}?\" frameborder=\"0\"></iframe>"
    end
    def normal_link(link)
      "<a href=\"#{link}\">#{link}</a>"
    end
    def email_link(email)
      "<a href=\"mailto:#{email}\">#{email}</a>"
    end
  end


  def markdown(text)
    coderayified = CodeRayify.new(escape_html: true, hard_wrap: true, with_toc_data: true)

    options = {
      no_intra_emphasis: true,
      tables: true,
      fenced_code_blocks: true,
      autolink: true,
      disable_indented_code_blocks: true,
      strikethrough: true,
      lax_spacing: true,
      space_after_headers: true,
      superscript: true,
      underline: true,
      highlight: true,
      quote: true,
      footnotes: true,
      lax_html_blocks: true,
      with_toc_data: true

    }

    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)

    markdown_to_html.render(text).html_safe
  end
end

app/views/resource_items/_admin_actions.html.haml
- if logged_in?(:site_admin)
  %nav.breadcrumb.blogcrumb
    = link_to toggle_status_resource_item_path(resource_item) do
      %i{'class' => 'fa fa-file-text breadcrumb-item', 'style' => resource_item_status_color(resource_item)}
    = link_to edit_resource_item_path(resource_item) do
      %i.fas.fa-pen
    = button_to @resource_item, :method => :delete, :data => { :confirm => "Are you sure you want to delete that post?" }, :class => 'button button--to-delete' do
      %i.fa.fa-trash.breadcrumb-item

app/views/resource_items/_cdong_task.html.erb
<!-- <iframe height="400px" width="100%" src="https://repl.it/repls/GoodSarcasticAdministrators?lite=true" scrolling="no" frameborder="no" allowtransparency="true" allowfullscreen="true" sandbox="allow-forms allow-pointer-lock allow-popups allow-same-origin allow-scripts allow-modals"></iframe> -->
<%= raw(@resource_item.cdong_task) %>

app/views/resource_items/_form.html.haml
%br
%br
%br
%br
%br
%br

= simple_form_for item do |f|
  - if item.errors.any?
    - item.errors.full_messages.each do |error|
      = alert_generator(error, :error, "Error")
  %div.form-group
    = f.label :title
    = f.text_field :title, cols: 100
  %div.form-group
    = f.label :created_at, "Publish Date"
    = f.date_field :created_at, value: (item.created_at || Time.now)
  %div.form-group
    / = f.input :resource_topic_id, collection: ResourceTopic.all.map{|topic| [topic.title, topic.id]}, selected: 1, "aria-label" => "Topic"
    = f.collection_select :resource_topic_id, ResourceTopic.all, :id, :title, {:prompt => "Please select a topic"}, "aria-label" => "Topic"
  %div.form-group
    = f.label :body
    = f.text_area :body, rows: 80, cols: 150
  %div.form-group
    = f.label :WrittenTask
    = f.text_area :written_task, rows: 8, cols: 150
  %div.form-group
    = f.label :CodingTask
    = f.text_area :cdong_task, rows: 8, cols: 150
  %div.form-group
    = f.label :WrittenTask
    = f.text_area :written_task, rows: 8, cols: 150
  / %div.form-group
  /   = f.label :checkbox
  /   = f.text_area :checkboxes, rows: 15, cols: 150
  %ul
    = f.fields_for :questions do |question_form|
      %div.form-group
        =question_form.label :Question
        =question_form.text_area :question_text, rows: 3, cols: 100
      %div.form-group
        =question_form.label :Option1
        =question_form.text_area :option1, rows: 3, cols: 100
      %div.form-group
        =question_form.label :Explanation1
        =question_form.text_area :explanation1, rows: 3, cols: 100
      %div.form-group
        =question_form.label :Option2
        =question_form.text_area :option2, rows: 3, cols: 100
      %div.form-group
        =question_form.label :Explanation2
        =question_form.text_area :explanation2, rows: 3, cols: 100
      %div.form-group
        =question_form.label :Option3
        =question_form.text_area :option3, rows: 3, cols: 100
      %div.form-group
        =question_form.label :Explanation3
        =question_form.text_area :explanation3, rows: 3, cols: 100
  %ul
    = f.fields_for :checkboxes do |box_form|
      %div.form-group
        =box_form.label :Task
        =box_form.text_area :label, rows: 1, cols: 100
  %div.form-group
    = f.input :photos, as: :file, input_html: { multiple: true }
  %div.form-group
    = f.submit


/ Addresses:
/   <ul>
/     <%= f.fields_for :addresses do |addresses_form| %>
/       <li>
/         <%= addresses_form.label :kind %>
/         <%= addresses_form.text_field :kind %>

/         <%= addresses_form.label :street %>
/         <%= addresses_form.text_field :street %>
/         ...
/       </li>
/     <% end %>
/   </ul>

app/views/resource_items/_resource_item.html.haml
.page-section
  %h3.section-title.topic-title= link_to resource_item.title, resource_item_path(resource_item)
  %p= "Published #{distance_of_time_in_words resource_item.created_at, Time.now} ago"
  %p= pluralize resource_item.resource_comments.count, "comment"

  = render partial: 'resource_items/admin_actions', locals: {:resource_item => resource_item}




/ # DONE

app/views/resource_items/edit.html.haml
%div
  %h1= "Editing #{@resource_item.title}"
  = render 'form', item: @resource_item

  = link_to 'View Post', @resource_item
  = link_to 'Back to item', resource_items_path


/ # DONE

app/views/resource_items/index.html.haml
%div
  .row.row--full-height.relative
    .row__medium-1-2
      = image_tag 'https://res.cloudinary.com/adelcloud/image/upload/v1583819796/christian-fregnan-pvyWk-nXDNs-unsplash_drhzer.jpg', :alt => 'Blog', :class => 'img--full-height img--background img--grayscaled'
      .overlay.overlay--dark-color
      .container.container--full-height.container--centered-vh
        %h1.section-title= "Classes"
.page-section
  .container
    %iframe{:height =>"400px", :width => "100%", :src => "https://repl.it/repls/GoodSarcasticAdministrators?lite=true", :scrolling => "no", :frameborder => "no", :allowtransparency => "true", :allowfullscreen => "true", :sandbox => "allow-forms allow-pointer-lock allow-popups allow-same-origin allow-scripts allow-modals"}
    = paginate @resource_items
    = render partial: 'resource_item', collection: @resource_items
    = paginate @resource_items

app/views/resource_items/new.html.haml
%div
  %h1= @page_title
  = render 'form', item: @resource_item
  = link_to 'Back to Class', resource_items_path

app/views/resource_items/show.html.haml
.row.row--short.relative
  .row__medium-1-2
    = image_tag 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80', :alt => 'Computer', :class => 'img--full-height img--background img--grayscaled'
    .overlay.overlay--dark-color
.page-section
  .container
    %h2.section-title= @resource_item.title
    %p= "Published #{distance_of_time_in_words(@resource_item.created_at, Time.now)} ago"
    %p= pluralize @resource_item.resource_comments.count, "comment"
    %nav.breadcrumb
      = link_to 'Classes', resource_topic_path(@resource_item.resource_topic_id), class: "breadcrumb-item"
      %span.breadcrumb-item.active= @resource_item.title
      - if logged_in?(:site_admin)
        %div
          = link_to edit_resource_item_path(@resource_item) do
            %i.fa.fa-pencil-square-o
          = button_to @resource_item, :method => :delete, :data => { :confirm => "Are you sure you want to delete that class?" }, :class => 'button button--to-delete' do
            %i.fa.fa-trash

    .generic-content-container
      / - @resource_item.photos.each do |photo|
      /   %li= cl_image_tag photo.key, height: 300, width: 400
      = markdown @resource_item.body
    / %h4.section-title= "Tasks"
    / = render partial: 'checkboxes/checkbox', collection: @resource_item.checkboxes.by_recent
    - if @resource_item.questions.count > 2
      %h4.section-title.topic-title= "Quiz"
      = render partial: 'questions/question', collection: @resource_item.questions.by_recent

    - if @resource_item.cdong_task != ""
      %h4.section-title.topic-title= "Coding"
    = render partial: 'cdong_task'
    - if @resource_item.written_task != nil
      %h4.section-title.topic-title= "Written tasks"
      %p= "Write your answer to the question below. If in doubt, refer to the materials above. I'll review the answers 😊"
      %p= "You can also post any links or questions about the topic"
      %p
        = markdown @resource_item.written_task
    #comments{"data-resource_item-id" => @resource_item.id}
      = render partial: 'resource_comments/resource_comment', collection: @resource_item.resource_comments.by_recent
    = render "resource_comments/resource_comment_form"