config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }


  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'ruby-on-rails-portfolio', to: 'portfolios#ruby_on_rails'
  get 'vue-portfolio', to: 'portfolios#vue'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'messages#new', as: 'new_message'
  post 'contact', to: 'messages#create', as: 'create_message'

  resources :topics, only: [:index, :show]
  resources :resources, only: [:index, :show]
  resources :resource_categories, only: [:index, :show]
  resources :resource_topics, only: [:index, :show]


  resources :blogs do
    member do
      get :toggle_status
    end
  end

  resources :resource_items, except: [:index] do
    resources :resource_comments
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.haml
%footer.footer
  .container
    %p= copyright_generator
    

app/views/shared/_application_nav.html.haml
%nav.navbar
  .container.container--full-height-until-medium
    = link_to "Adel Muursepp", root_path, :class => "navbar__logo"
    .navbar__menu-icon
      %i.navbar__menu-icon__bars
    .navbar__menu-content
      %ul
        = nav_helper "", "li"

app/views/shared/_blog_footer.html.haml
%footer
  %p= copyright_generator
  %p= link_to "Back to Top", "#"

app/views/shared/_blog_masthead.html.haml
%h1= "Adel's Blog"
%p= "Web design, development and business."
= link_to "Write a New Post", new_blog_path if logged_in?(:site_admin)

app/views/shared/_blog_nav.html.haml
%h4= "Full Stack Web Development"
%p= "I am able to work with users and developers, across the stack and at various points of the creative process."
%h4= "Explore"
%ul
  = nav_helper "", "li"
  = login_helper "", "li"
= link_to "Adel Muursepp", root_path

app/views/shared/_blog_sidebar.html.haml
%div
  %h4= link_to "About", about_path
  = image_tag "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80", :alt => "profile image"
  %p= "My name is Adel Muursepp and I work as a freelancer"
  = source_helper "alert alert-info"
  %h4= "Elsewhere"
  %ol
    %li= link_to fa_icon("github"), "https://github.com/adelmuursepp"
    %li= link_to fa_icon("linkedin"), "https://www.linkedin.com/in/adel-muursepp"
  %h4= link_to "Topics", topics_path
  %ol
    - @all_topics.each do |topic|
      %li= link_to topic.title, topic

app/views/shared/_nav.html.haml
%div{:class => location}
  %span= link_to "Home", root_path
  %span= link_to "About", about_path
  %span= link_to "Portfolio", portfolios_path
  %span= link_to "Contact", contact_path
  %span= link_to "Blog", blogs_path
  %span= link_to "Resources", resources_path

app/views/shared/_portfolio_footer.html.haml
%footer
  %p
    = link_to "Add new project | ", new_portfolio_path if logged_in?(:site_admin)
    = link_to "View all projects", portfolios_path
    = link_to "Back to top", "#"
  %p= copyright_generator
    

app/views/shared/_portfolio_masthead.html.haml
%h1= "Adel's Portfolio"
%p= "Here you'll find samples of the work I've done, from graphic and web design to front- and back-end development."
%p
  = link_to "About Me", about_path
  = link_to "Contact Me", new_message_path

app/views/shared/_portfolio_nav.html.haml
%h4= "Full Stack Web Development"
%p= "I am able to work with users and developers, across the stack and at various points of the creative process."
%h4= "Explore"
%ul
  = nav_helper "", "li"
  = login_helper "", "li"
= link_to "Adel Muursepp", root_path